project:
  type: website

website:
  title: "Caleb Kendra"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: 
        light: flatly
        dark: darkly
    css: styles.css
    toc: true



