---
title: "Software Engineering at Google - 1"
date: 09/04/2023
date-format: long
author: Caleb J. Kendra
categories: Software Engineering at Google
subtitle: Programming Over Time
title-block-banner: true
---

# Summary

In the preface of "Software Engineering at Google" in the Programming Over Time section we are first introduced to the idea that "Software Engineering" is not just the act of creating code, but also the creation of processes that allow us to create maintainable and sustainable code. In this sense, when we release a version of the software we created, we don't want that software to be the final version but rather a building block upon which we can improve. In order to succeed in this goal of sustainability the book is going to emphasize three points to be thinking of while creating software:

- Time - We need to plan out how the software we create will change from the start and finish of a certain project

- Scale - We also need to plan how we will change our engineering methods as our team of engineers develops.

- Costs - Then we also need to decide on what parts of the project should be prioritized over others.

# Reflection

As I think about how this section compares to `chasten` two main points jump out at me. For starters, the scaling of the project is going to be very important in order to make sure our code is created sustainably and on time. Since this project is being developed by a group of students who have for the most part never worked on a project at this scale or at this size of a team, plans are going to be have to laid out carefully. This is so everyone in our team stays on task and knows what they are doing as the project grows.

The other point I want to make is about the cost of certain features leading to decisions on what should be prioritized. This should also be something we should always be thinking of as well because we only have half a semester do work on `chasten`'s features and in order to make sure we deliver a functioning product we need to make sure that we are only working on the most important features.

# Action Items

After reading this section it is clear to me that in big groups of software engineers, we need to be making a plan early on in order to make sure that every member of our team knows precisely what the plan for the codebase is. Then, adequate communication will allow our team to make quick decisions on what code should be made and how it should be made. On the other hand, it is clear to me that I need to quit keeping coding and software solutions to myself and should spread these to other people. This will allow for greater levels of communication between team members and will allow this project to succeed as a whole.