---
title: "Software Engineering at Google - 6"
date: 10/19/2023
date-format: long
author: Caleb J. Kendra
categories: Software Engineering at Google
subtitle: How to Lead a Team
title-block-banner: true
---

# Summary

This section in `Software Engineering at Google` recognizes the need to have a leader for every team as a team is nothing without someone to steer them in the right direction. With the manager of a software developer team being such a important role, engineers who never expected or wanted to go into management find themselves either directly or indirectly in these positions. This is why it is important to learn how to not only be a good software engineer, but also how to manage a team of engineers. 

One of the big first points that are made are about trying not to over manage your team when you are managing. You don't want to be micromanaging and making your engineers lives harder, so it is better to focus on making the lives of your engineers smoother. Instead of harming and squeezing the most our of your workers, it is more productive to give your workers time and space in order to create a positive work enviroment. One way of doing this is to give your workers the leeway in order to work whenever they want as long as they are getting their work done, allowing for workers to work on their own time schedule. Another big concept is to not be a friend to all of your workers as you will have to give them hard information and make sure they are keeping on task. Being a positive, calm, and down-to-earth manager helps you work with your workers in order to be a great resource for people to use. This will help you break down roadblocks and make the process easier for workers to focus on work instead of outside problems. These ideas culminate in three main ideas of:

- Humility
- Trust
- Respect

If you follow these three main ideas you will help all your workers by being a strong source that can be relied on and allow your workers to focus on the task at hand rather then worrying about their manager.

# Action & Reflection

We do not have any direct leaders of certain groups, but as a team we do have to lead each other in certain projects especially when we are specialiced in certain parts of the code and we have to share this with others. That being said, there is not a power structure like manager down to worker such as in a big buisness and so many of the power structure ideas do not apply here. However, we can still be respectfull and make sure to be humble when dealing wiht people who are less prepared or knowledgeable about a certain topic then us, this will allow for better knowledge transfer.
